server:
  port: 8082

spring:
  application:
    name: customer

  doc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
      path: /swagger-ui.html

  datasource:
    url: jdbc:postgresql://db:5432/customer
    username: customer_user
    password: customer_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
